function [f] = int_feature(x)
f = [];
  
feat = {
    'msr'    ,...
    'lcov'  ,...
    'fzc',...
    'ewl'    ,...
    'emav'   ,...
    'asm'    ,...
    'ass'  ,...
    'ltkeo'  ,...
    'card'   ,...
    'ldasdv' ,...
    'ldamv'  ,...
    'dvarv'  , ...
    'mfl'   ,...
    'myop'   ,...
    'ssi'    ,...
    'vo'     ,... 
    'tm'    ,...
    'aac'   ,...
    'mmav'   ,...
    'mmav2'  ,...
    'iemg'  ,...
    'dasdv'  ,...
    'damv'   ,...
    'rms'    , ...
    'vare'   ,...
    'wa'     ,...
    'ld'     ,...
    'ar'     ,...
    'mav'    ,...
    'zc'     ,...
    'ssc'    ,...
    'wl'    ,...
    'mad'    ,...
    'iqr'    , ...
    'kurt'   ,...
    'skew'  ,...
    'cov'    ,...
    'sd'     ,...
    'var'    ,...
    'ae'    };

L = 100;
for ff = feat
    fn = jfemg(ff{1}, x);
    f = [f real(fn)];
end

% =====================
% FFT-based features
% =====================
Y = fft(x);
P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2 * P1(2:end-1);

decomplevels = 6;
wv = "db2";
[c,l] = wavedec(x, decomplevels, wv);
[Ea,Ed] = wenergy(c,l);

t = wpdec(x, 3, wv);
e = wenergy(t);

f = [mean(P1), median(P1), max(P1), Ed, e, f];
end
